### ISSUE TITLE
Using strings for SIR lookups isn't ideal

### ISSUE THREAD

**Issue by ltratt** [ykjit/yk#284] opened 2021-03-04 12:58 UTC
For example we have things like:

```rust
pub fn body(&self, body_sym: &str) -> Option<Arc<Body>>
```

String lookups are slow *and* they cause some almighty contortions in places where we have to create strings from nowhere (e.g. the StopgapInterpreter). It would be much easier if we looked SIR elements up by something that's `Copy`able (i.e. an integer). That suggests that we need something like `SIRId` which is probably a `usize` or similar in disguise. We can then have them something like `symbol_to_sirid(sym: &str) -> SirId` but hopefully we don't have to use that very often.

**Comment by vext01** [comment] 2021-03-04 13:31
Duplicate of #251 ?

**Comment by ltratt** [comment] 2021-03-04 13:32
Very similar, but #251 seems to suggest that we have duplicate names stored in the binary? My worry is more that we're duplicating strings at run-time. That said, solving either of these issues will probably solve the other.

**Comment by vext01** [comment] 2021-06-24 14:18
Closing, as this is for the old yk design.

**Closed by vext01** 2021-06-24 14:18 UTC
