### ISSUE TITLE
HW/SW tracers shouldn't be an either/or compile-time switch

### ISSUE THREAD

**Issue by ltratt** [ykjit/yk#300] opened 2021-03-24 12:08 UTC
It makes sense that on some platforms we can't even try compiling HW tracing in (e.g. let's assume that RISC-V currently doesn't have adequate support: we wouldn't try including any HW tracing support, let alone, Intel PT support, on that platform!). However I think it often (maybe even always) makes sense to have software tracing alongside support for one or more HW tracing. I think we need to move to a more run-time configuration of these things.

As a concrete example, imagine I want to distribute an x86 binary of ykbs. To ensure that it runs on as many x86 systems as possible I'd probably want that binary to have all three of:

* Software tracing
* Intel PT support
* Whatever the AMD equivalent of PT might be (assuming there is one)

I'd also like that binary to auto-detect what system it's running on and select the best mechanism appropriately (unless I dynamically force it to use a different version).

This suggests that code like the following:

```rust
    #[cfg(tracermode = "hw")]
    let th = start_tracing(TracingKind::HardwareTracing);
    #[cfg(tracermode = "sw")]
    let th = start_tracing(TracingKind::SoftwareTracing);
    ...
    let sir_trace = th.stop_tracing().unwrap();
```

isn't really the right way of thinking about it. First we will have multiple types of hardware tracing. I *think* we'll probably only have one type of software tracing, but that might be a lack of imagination on my part: unless we're convinced that there can only be one type, we could even make that configurable if we want.

Rather we should presumably have something like:

```
let tracer = TraceBuilder::new().build().unwrap();
tracer.start();
...
tracer.stop();
```

and if you want a specific tracer at run-time then you can do something like:

```
let tracer = TraceBuilder::new().tracer(TracingKind::IntelPT).build().unwrap();
```

If the machine that binary is running on doesn't support Intel PT then the `unwrap` will abort the process.

If at the moment we can't build these different things, then it's probably at least worth us changing the API so that when we can can, we don't have to change *too* much code.

**Comment by bjorn3** [comment] 2021-03-24 12:21
> Intel PT support
> Whatever the AMD equivalent of PT might be (assuming there is one)

These would likely need the same metadata, so everything that would be necessary to support both would be to have a switch on the processor vendor inside the hardware tracing start function I think. Mixing software and hardware tracing without performance loss on hardware tracing would need functions to be duplicated though. This is going to be tough in the presence of function pointer though I think.

**Comment by ltratt** [comment] 2021-03-24 12:25
> These would likely need the same metadata, so everything that would be necessary to support both would be to have a switch on the processor vendor inside the hardware tracing start function I think.

That's my working guess too. By moving the interface to a run-time thing, we don't even have to really worry about this: you can only select the options that the binary was compiled with (whatever they were).

>Mixing software and hardware tracing without performance loss on hardware tracing would need functions to be duplicated though.

I agree that it will probably bloat the binary, but I'm not sure it will definitely lead to a performance loss. That said, it might be too difficult to enable. In that case, we might have to settle with training users to expect two binarys e.g. `ykbf-hw` and `ykbf-sw` and then have a wrapper `ykbf` which `exec`s the right one.

**Comment by bjorn3** [comment] 2021-03-24 13:18
I mean to avoid a performance loss you need to have a software traced and non-software traced version of functions. The overhead of a TLS access on every block entry is huge. The lowest overhead I got with cg_clif a while ago was ~30%: https://chat.soft-dev.org/yk/pl/ij4z8bx8mt8mx8q1k64698i4ae The overhead of a single call + retq on every block is ~15%, which is the lower bound on the performance impact I think: https://chat.soft-dev.org/yk/pl/4xhi3kfpnt88jy7rq5b1b7s58e

**Comment by vext01** [comment] 2021-03-24 13:19
This is a duplicate of [this](https://github.com/softdevteam/ykrustc/issues/51).

It's not an easy change and I don't recommend we do it now.

> let tracer = TraceBuilder::new().build().unwrap();

We have `TracingKind::default()`, but it's not very extensively used.

**Comment by ltratt** [comment] 2021-03-24 13:20
I'm not proposing we do the hard underlying work now, but moving to a run-time switch along the lines I suggested (`TraceBuilder`) shouldn't be too difficult should it?

**Comment by vext01** [comment] 2021-03-24 13:24
Do you mean, have a TracerBuilder which bombs out if you choose a kind of tracing that you didn't compile for?

**Comment by ltratt** [comment] 2021-03-24 13:25
Yes but with the qualification that unless you explicitly choose a different type of tracer, `TracerBuilder` will select what it thinks is the best tracer for your situation. In other words, virtually nobody will ever manually choose the tracer.

**Comment by vext01** [comment] 2021-03-24 13:29
OK, I'm with you now.

That's what [`TracingKind::default()`](https://github.com/softdevteam/yk/blob/cb6b79002656837a4ddee3d9263fcaefa04a376b/internal_ws/yktrace/src/lib.rs#L28-L36) does, but a) lots of tests don't use it (I'm not sure it's exposed via the shim yet), and b) it doesn't yet allow for different implementations of hardware or software tracing.

I don't mind that being changed.

**Comment by ltratt** [comment] 2021-03-24 13:32
@ptersilie Might you be willing to take this one on at some point?

**Comment by ptersilie** [comment] 2021-03-24 15:31
I can put it on my list.

**Comment by ltratt** [comment] 2021-03-24 15:33
Thanks!

**Comment by vext01** [comment] 2021-06-24 14:17
Closing, as this is for the old yk design.

**Closed by vext01** 2021-06-24 14:17 UTC
